import Head from "next/head";
import { Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "@/components/navbar";
import Banner from "@/components/banner/banner";
import MainCars from "@/components/main-cars/main-cars";
import { Box } from "@mantine/core";
import Footer from "@/components/footer";

export const jakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={jakartaSans.className}>
        <Navbar />
        <Box px={64} bg="#F6F7F9">
          <Banner />
          <MainCars />
        </Box>
        <Footer />
      </main>
    </>
  );
}
