import Sidebar from "@/components/catalogue/sidebar";
import Description from "@/components/detail-cars/description";
import Gallery from "@/components/detail-cars/gallery";
import Recommendation from "@/components/detail-cars/recommendation";
import Review from "@/components/detail-cars/reviews";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { jakartaSans } from "@/pages";
import { SimpleGrid } from "@mantine/core";
import Head from "next/head";
import React from "react";

export default function Detail() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={jakartaSans.className}>
        <Navbar />
        <Sidebar>
          <SimpleGrid cols={2}>
            <Gallery />
            <Description />
          </SimpleGrid>
          <Review />
          <Recommendation />
          <Recommendation />
        </Sidebar>
        <Footer />
      </main>
    </>
  );
}
